## Importing required libraries

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

##  Ranking hospitals by outcome in a state

In [73]:
def rank_all_hospital (outcome,Rank):
    file = pd.read_csv('outcome-of-care-measures.csv')
    # all columns are character columns-data values are in string format
    list_csv_col = [file.columns[1], file.columns[6],file.columns[10], file.columns[16],
                    file.columns[22]]
    df = pd.DataFrame(data = file[list_csv_col]) # converting data into dataframe
    df.columns = ['Hospital.Name','State','Heart.attack', 'Heart.failure','Pneumonia'] # naming 
    # columns
    new_dict = {"States":[],"Hospitals":[], "Rank":[]}# creating dictionary
    
    if outcome not in df.columns[2:5]: # if a outcome is present in column 2-5
         return ("Invalid outcome")
        
    else:
       
        for state in sorted(df['State'].unique()): # list of unique values of state
            new_dict["States"].append(state) # adding state to the dictinary's key"States"
            df1 = df[(df['State'] ==state)][['State','Hospital.Name',outcome]] # slicing dataframe
            # based on condition
            
            # converting character column (numbers are in string format) to numeric,and 
            # replacing missing values and string (in this case 'Not Available') into NAN 
            # (setting errors=â€™coerce)
            df1[outcome]= pd.to_numeric(df1[outcome],errors='coerce') 
            
            df1 = df1.dropna(subset =[outcome]) # droping NAN in outcome column
            df1 = df1.sort_values(by = [outcome,'Hospital.Name']) # sorting dataframe by 
            # Hopsital.name first then by outcome
            
            df1.index = [i for i in range(1, df1.shape[0]+1)] # creating index valuse from 
            # 1 to no. of rows [df1.shape[0]] 

            try:
                rank = int(Rank) # if rank is integer

                if rank > df1.shape[0]: # if rank is not present in the index = no of rows
                    # (df1.shape[0])
                    
                    new_dict["Rank"].append("NA") # adding "NA" to the dictinary's key "Rank" 
                    # if the rank is not present in dataframe
                    
                    new_dict["Hospitals"].append("NA") # adding "NA" to the dictinary's key"
                    # Hospitals" (no hospital of this rank)

                else: # if rank is present in the index = no of rows(df1.shape[0])
                    new_dict["Rank"].append(rank) # adding rank value to the dictinary's 
                    # key "Rank"
                    
                    hospital_name = df1.at[rank,'Hospital.Name'] # extarcting observation 
                    # correspond to [row index, column index]
                    
                    new_dict["Hospitals"].append(hospital_name) # adding "hospital_name" to 
                    # the dictinary's key"Hospitals" 

            except ValueError:   # if rank is string
                rank = str(Rank)
                
                if rank =='best':
                    new_dict["Rank"].append("best") # adding "best" to the dictinary's key "Rank"
                    hospital_name = df1.at[1,'Hospital.Name'] # extarcting observation correspond 
                    # to [1, column index]
                    
                    new_dict["Hospitals"].append(hospital_name) # adding "hospital_name" to the
                    # dictinary's key"Hospitals" 

                if rank =='worst':
                    new_dict["Rank"].append("worst")
                    hospital_name = df1.at[df1.shape[0],'Hospital.Name']  # extarcting observation
                    # correspond to [last index, column index]
                    
                    new_dict["Hospitals"].append(hospital_name)# adding "hospital_name" to the 
                    # dictinary's key"Hospitals" 

    data_frame =pd.DataFrame(new_dict) # converting dictionary in to dataframe
    return(data_frame.head(10)) # ouputting dataframe

In [68]:
rank_all_hospital("Heart.attack",'best')

  States                             Hospitals  Rank
0     AK      PROVIDENCE ALASKA MEDICAL CENTER  best
1     AL              CRESTWOOD MEDICAL CENTER  best
2     AR               ARKANSAS HEART HOSPITAL  best
3     AZ                  MAYO CLINIC HOSPITAL  best
4     CA     GLENDALE ADVENTIST MEDICAL CENTER  best
5     CO  ST MARYS HOSPITAL AND MEDICAL CENTER  best
6     CT                    WATERBURY HOSPITAL  best
7     DC                   PROVIDENCE HOSPITAL  best
8     DE     BAYHEALTH - KENT GENERAL HOSPITAL  best
9     FL            MOUNT SINAI MEDICAL CENTER  best

In [74]:
rank_all_hospital("Heart.failure",'worst')

  States                               Hospitals   Rank
0     AK             FAIRBANKS MEMORIAL HOSPITAL  worst
1     AL          DEKALB REGIONAL MEDICAL CENTER  worst
2     AR           NEA BAPTIST MEMORIAL HOSPITAL  worst
3     AZ       MT GRAHAM REGIONAL MEDICAL CENTER  worst
4     CA         CLOVIS COMMUNITY MEDICAL CENTER  worst
5     CO  CENTURA HEALTH-ST THOMAS MORE HOSPITAL  worst
6     CT            MANCHESTER MEMORIAL HOSPITAL  worst
7     DC          GEORGETOWN UNIVERSITY HOSPITAL  worst
8     DE                    BEEBE MEDICAL CENTER  worst
9     FL               MANATEE MEMORIAL HOSPITAL  worst

In [75]:
rank_all_hospital("Heart.failure",'8')

  States                                Hospitals Rank
0     AK         PROVIDENCE ALASKA MEDICAL CENTER    8
1     AL                FLORALA MEMORIAL HOSPITAL    8
2     AR  BAPTIST HEALTH MEDICAL CENTER-STUTTGART    8
3     AZ              VERDE VALLEY MEDICAL CENTER    8
4     CA         DOCTORS MEDICAL CENTER-SAN PABLO    8
5     CO     SPANISH PEAKS REGIONAL HEALTH CENTER    8
6     CT                    JOHN DEMPSEY HOSPITAL    8
7     DC                                       NA   NA
8     DE                                       NA   NA
9     FL                         FLAGLER HOSPITAL    8

In [76]:
rank_all_hospital("Hepatitis",'8')

'Invalid outcome'